apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: factorial-service
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'factorial-service-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - factorial-service
        relabel_configs:
          # Solo pod con label app=factorial-service
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: factorial-service
          # Usa pod IP:8001 per metrics
          - source_labels: [__meta_kubernetes_pod_ip]
            action: replace
            target_label: __address__
            replacement: ${1}:8001
          # Aggiungi pod name come label
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod_name
          # Aggiungi pod IP come label
          - source_labels: [__meta_kubernetes_pod_ip]
            action: replace
            target_label: pod_ip
        scrape_interval: 5s
        metrics_path: /metrics
      

      - job_name: 'factorial-service-aggregated'
        static_configs:
          - targets: ['factorial-service:8001']
        scrape_interval: 5s
        metrics_path: /metrics
        

      - job_name: 'kubernetes-cadvisor'
        scheme: https
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
            
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system:8080']