apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prime-service
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # Scrape del tuo servizio prime-service
      - job_name: 'prime-service'
        static_configs:
          - targets: ['prime-service:8001']
        scrape_interval: 5s
        metrics_path: /metrics
        
      # Scrape di cAdvisor per metriche container
      - job_name: 'kubernetes-cadvisor'
        scheme: https
        authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
            
      # Scrape di kube-state-metrics per metriche Kubernetes
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system:8080']