apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prime-service  
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090