apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorial-service
  namespace: factorial-service
spec:
  # 1) Imposta qui quante repliche vuoi distribuire
  replicas: 4
  selector:
    matchLabels:
      app: factorial-service
  template:
    metadata:
      labels:
        app: factorial-service
    spec:
      affinity:
        podAntiAffinity:
          # 2) Usando "preferred" lo spreading è un consiglio, non un blocco
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - factorial-service
              topologyKey: kubernetes.io/hostname
      containers:
      - name: factorial-service
        image: factorial-service:v1.0.1
        imagePullPolicy: IfNotPresent  
        ports:
        - containerPort: 8000
        
        resources:
          requests:
            cpu: "0.5"
            memory: "128Mi"
          limits:
            cpu: "1.5"
            memory: "512Mi"  
        
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        
        readinessProbe:
          httpGet:
            path: /factorial/10
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
