apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorial-service
  namespace: factorial-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorial-service
  template:
    metadata:
      labels:
        app: factorial-service
    spec:
      containers:
      - name: factorial-service
        image: factorial-service:v1.0.0
        imagePullPolicy: Never  
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "500m"      # 0.5 core
            memory: "128Mi"
          limits:
            cpu: "2000m"     # 2 core
            memory: "512Mi"  
        readinessProbe:
          httpGet:
            path: /factorial/10
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10