apiVersion: v1
kind: Service
metadata:
  name: prime-service
  namespace: prime-service
spec:
  selector:
    app: prime-service
  type: LoadBalancer
  sessionAffinity: None
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  - name: metrics
    protocol: TCP
    port: 8001
    targetPort: 8001