apiVersion: v1
kind: Service
metadata:
  name: factorial-service
  namespace: factorial-service
spec:
  selector:
    app: factorial-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  - name: metrics
    protocol: TCP
    port: 8001
    targetPort: 8001
  type: LoadBalancer 
  sessionAffinity: None