apiVersion: v1
kind: Service
metadata:
  name: factorial-service
  namespace: factorial-service
spec:
  selector:
    app: factorial-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30080  # Porta esposta sui nodi
  - name: metrics
    protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 30081  # Porta per metriche Prometheus
  type: NodePort
  sessionAffinity: None